package corba;

/**
* TicTakTicket/corba/CobraExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public final class CobraExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.CobraException value = null;

  public CobraExceptionHolder ()
  {
  }

  public CobraExceptionHolder (corba.CobraException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.CobraExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.CobraExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.CobraExceptionHelper.type ();
  }

}
