package corba;


/**
* TicTakTicket/corba/CobraException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public final class CobraException extends org.omg.CORBA.UserException
{
  public String message = null;

  public CobraException ()
  {
    super(CobraExceptionHelper.id());
  } // ctor

  public CobraException (String _message)
  {
    super(CobraExceptionHelper.id());
    message = _message;
  } // ctor


  public CobraException (String $reason, String _message)
  {
    super(CobraExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class CobraException
