package corba;

/**
* TicTakTicket/corba/CorbaConterollerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public final class CorbaConterollerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.CorbaConterollerInterface value = null;

  public CorbaConterollerInterfaceHolder ()
  {
  }

  public CorbaConterollerInterfaceHolder (corba.CorbaConterollerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.CorbaConterollerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.CorbaConterollerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.CorbaConterollerInterfaceHelper.type ();
  }

}
