package corba;


/**
* TicTakTicket/corba/CorbaConterollerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

abstract public class CorbaConterollerInterfaceHelper
{
  private static String  _id = "IDL:TicTakTicket/corba/CorbaConterollerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.CorbaConterollerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.CorbaConterollerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corba.CorbaConterollerInterfaceHelper.id (), "CorbaConterollerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.CorbaConterollerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CorbaConterollerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.CorbaConterollerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corba.CorbaConterollerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.CorbaConterollerInterface)
      return (corba.CorbaConterollerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._CorbaConterollerInterfaceStub stub = new corba._CorbaConterollerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corba.CorbaConterollerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.CorbaConterollerInterface)
      return (corba.CorbaConterollerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._CorbaConterollerInterfaceStub stub = new corba._CorbaConterollerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
