package corba;


/**
* TicTakTicket/corba/CorbaConterollerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public abstract class CorbaConterollerInterfacePOA extends org.omg.PortableServer.Servant
 implements corba.CorbaConterollerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getAlleFreieKartenNachKategorie", new java.lang.Integer (0));
    _methods.put ("getKategorieInfoVonVeranstaltung", new java.lang.Integer (1));
    _methods.put ("sucheVeranstaltungNachKriterien", new java.lang.Integer (2));
    _methods.put ("verkaufSpeichern", new java.lang.Integer (3));
    _methods.put ("getKategorieInfo", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //falls null nicht geht einzelne Methoden mit jedem Parameter machen
       case 0:  // TicTakTicket/corba/CorbaConterollerInterface/getAlleFreieKartenNachKategorie
       {
         corba.StructKategorieAuswaehlen kategorie = corba.StructKategorieAuswaehlenHelper.read (in);
         corba.StructKategorieKarte $result = null;
         $result = this.getAlleFreieKartenNachKategorie (kategorie);
         out = $rh.createReply();
         corba.StructKategorieKarteHelper.write (out, $result);
         break;
       }

       case 1:  // TicTakTicket/corba/CorbaConterollerInterface/getKategorieInfoVonVeranstaltung
       {
         corba.StructVeranstaltungAnzeigen veranstaltung = corba.StructVeranstaltungAnzeigenHelper.read (in);
         corba.StructKategorieInformation $result[] = null;
         $result = this.getKategorieInfoVonVeranstaltung (veranstaltung);
         out = $rh.createReply();
         corba.CorbaConterollerInterfacePackage.kategorieListHelper.write (out, $result);
         break;
       }

       case 2:  // TicTakTicket/corba/CorbaConterollerInterface/sucheVeranstaltungNachKriterien
       {
         String datum = in.read_string ();
         String ort = in.read_string ();
         String kuenstler = in.read_string ();
         corba.StructVeranstaltung $result[] = null;
         $result = this.sucheVeranstaltungNachKriterien (datum, ort, kuenstler);
         out = $rh.createReply();
         corba.CorbaConterollerInterfacePackage.veranstaltungListHelper.write (out, $result);
         break;
       }

       case 3:  // TicTakTicket/corba/CorbaConterollerInterface/verkaufSpeichern
       {
         try {
           corba.StructKarteBestellen karten[] = corba.CorbaConterollerInterfacePackage.bestellungListHelper.read (in);
           this.verkaufSpeichern (karten);
           out = $rh.createReply();
         } catch (corba.CobraException $ex) {
           out = $rh.createExceptionReply ();
           corba.CobraExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // TicTakTicket/corba/CorbaConterollerInterface/getKategorieInfo
       {
         int id = in.read_long ();
         corba.StructKategorieInformation $result = null;
         $result = this.getKategorieInfo (id);
         out = $rh.createReply();
         corba.StructKategorieInformationHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TicTakTicket/corba/CorbaConterollerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CorbaConterollerInterface _this() 
  {
    return CorbaConterollerInterfaceHelper.narrow(
    super._this_object());
  }

  public CorbaConterollerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CorbaConterollerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CorbaConterollerInterfacePOA
