package corba;


/**
* TicTakTicket/corba/CorbaConterollerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public interface CorbaConterollerInterface extends CorbaConterollerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaConterollerInterface
