package corba;

/**
* TicTakTicket/corba/StructVeranstaltungHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public final class StructVeranstaltungHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.StructVeranstaltung value = null;

  public StructVeranstaltungHolder ()
  {
  }

  public StructVeranstaltungHolder (corba.StructVeranstaltung initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.StructVeranstaltungHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.StructVeranstaltungHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.StructVeranstaltungHelper.type ();
  }

}
