package corba;


/**
* TicTakTicket/corba/StructKarte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public final class StructKarte implements org.omg.CORBA.portable.IDLEntity
{
  public int kartenId = (int)0;
  public String reihe = null;
  public int platz = (int)0;

  public StructKarte ()
  {
  } // ctor

  public StructKarte (int _kartenId, String _reihe, int _platz)
  {
    kartenId = _kartenId;
    reihe = _reihe;
    platz = _platz;
  } // ctor

} // class StructKarte
