package corba;

/**
* TicTakTicket/corba/StructKarteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public final class StructKarteHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.StructKarte value = null;

  public StructKarteHolder ()
  {
  }

  public StructKarteHolder (corba.StructKarte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.StructKarteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.StructKarteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.StructKarteHelper.type ();
  }

}
