package corba;


/**
* TicTakTicket/corba/StructKarteBestellen.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public final class StructKarteBestellen implements org.omg.CORBA.portable.IDLEntity
{
  public int kartenId = (int)0;
  public int kundenId = (int)0;
  public boolean ermaessigt = false;

  public StructKarteBestellen ()
  {
  } // ctor

  public StructKarteBestellen (int _kartenId, int _kundenId, boolean _ermaessigt)
  {
    kartenId = _kartenId;
    kundenId = _kundenId;
    ermaessigt = _ermaessigt;
  } // ctor

} // class StructKarteBestellen
