package corba;


/**
* TicTakTicket/corba/StructKategorieInformation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public final class StructKategorieInformation implements org.omg.CORBA.portable.IDLEntity
{
  public int kategId = (int)0;
  public String katName = null;
  public double katPreis = (double)0;

  //typdef fixed<9,2> katPreis;  wird von idlj nicht unterstuetzt
  public int freiePlaetze = (int)0;
  public int ermaessigung = (int)0;

  public StructKategorieInformation ()
  {
  } // ctor

  public StructKategorieInformation (int _kategId, String _katName, double _katPreis, int _freiePlaetze, int _ermaessigung)
  {
    kategId = _kategId;
    katName = _katName;
    katPreis = _katPreis;
    freiePlaetze = _freiePlaetze;
    ermaessigung = _ermaessigung;
  } // ctor

} // class StructKategorieInformation
