package corba;


/**
* TicTakTicket/corba/StructKategorieAuswaehlen.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TicTakTicket.idl
* Mittwoch, 20. November 2013 20:15 Uhr MEZ
*/

public final class StructKategorieAuswaehlen implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;

  public StructKategorieAuswaehlen ()
  {
  } // ctor

  public StructKategorieAuswaehlen (int _id)
  {
    id = _id;
  } // ctor

} // class StructKategorieAuswaehlen
